version: "3.9"

services:

  db:
    image: postgres:16-alpine
    container_name: compuroom-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: compuroom

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend

    container_name: compuroom-api

    restart: always

    depends_on:
      - db

    ports:
      - "3001:3001"

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: compuroom
      PORT: 3001

volumes:
  postgres_data: